# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59673e347e1ae40d2295d6cf6eb8fbac69a2a0fdc16ae1bc8082fc721fc9468d20caa739e256f89714e262993654e4bcc882ab0a25148f05fad62e217e9d9751

test:
  secret_key_base: 0b38abb7b4a7dfdfa3792af24fd31b708dc890a42752ac0f9c955b2db4f233b766e098dd5f2b8f95928692b2eb15dfef625f1295b84f2975882873c51dd757a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
